// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 //* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
package com.mono_car_rent.modules.rental;

public class PayRental extends javax.swing.JFrame {

    /**
     * Creates new form PayRental
     */
    public PayRental() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPagoArriendo = new javax.swing.JPanel();
        tituloCuotasArriendo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaArriendo = new javax.swing.JList<>();
        fechaArriendo = new javax.swing.JLabel();
        guardarMostrarCuotas = new javax.swing.JButton();
        labelPagos = new javax.swing.JLabel();
        tituloNumero = new javax.swing.JLabel();
        tituloValor = new javax.swing.JLabel();
        tituloPagada = new javax.swing.JLabel();
        panelCuotas = new javax.swing.JScrollPane();
        listaPagos = new javax.swing.JList<>();
        botonPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(782, 424));
        setPreferredSize(new java.awt.Dimension(782, 424));

        tituloCuotasArriendo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloCuotasArriendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCuotasArriendo.setText("PAGAR CUOTAS DE ARRIENDOS");
        tituloCuotasArriendo.setToolTipText("");

        jComboBox1.setBackground(new java.awt.Color(220, 220, 220));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione clientes", "Item 1", "Item 2", "Item 3", "Item 4" }));

        listaArriendo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaArriendo.setToolTipText("");
        jScrollPane1.setViewportView(listaArriendo);

        fechaArriendo.setText("Seleccione arriendo:");

        guardarMostrarCuotas.setBackground(new java.awt.Color(220, 220, 220));
        guardarMostrarCuotas.setText("Mostrar pagos arriendo seleccionado >>>");
        guardarMostrarCuotas.setAutoscrolls(true);
        guardarMostrarCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMostrarCuotasActionPerformed(evt);
            }
        });

        labelPagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPagos.setText("P A G O S");

        tituloNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNumero.setText("Numero");
        tituloNumero.setToolTipText("");

        tituloValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloValor.setText("Valor");
        tituloValor.setToolTipText("");

        tituloPagada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloPagada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPagada.setText("¿pagada?");
        tituloPagada.setToolTipText("");

        panelCuotas.setViewportView(listaPagos);

        botonPagar.setBackground(new java.awt.Color(220, 220, 220));
        botonPagar.setText("Realizar Pago");

        javax.swing.GroupLayout panelPagoArriendoLayout = new javax.swing.GroupLayout(panelPagoArriendo);
        panelPagoArriendo.setLayout(panelPagoArriendoLayout);
        panelPagoArriendoLayout.setHorizontalGroup(
            panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCuotasArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(fechaArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                        .addComponent(guardarMostrarCuotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                                            .addComponent(tituloNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(tituloValor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(tituloPagada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(panelCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoArriendoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonPagar)
                                .addGap(27, 27, 27)))
                        .addGap(20, 20, 20))
                    .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelPagoArriendoLayout.setVerticalGroup(
            panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoArriendoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tituloCuotasArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                        .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloNumero)
                            .addComponent(tituloValor)
                            .addComponent(tituloPagada))
                        .addGap(6, 6, 6)
                        .addComponent(panelCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                        .addComponent(labelPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaArriendo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPagoArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPagoArriendoLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(guardarMostrarCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(botonPagar)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPagoArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPagoArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarMostrarCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMostrarCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarMostrarCuotasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPagar;
    private javax.swing.JLabel fechaArriendo;
    private javax.swing.JButton guardarMostrarCuotas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPagos;
    private javax.swing.JList<String> listaArriendo;
    private javax.swing.JList<String> listaPagos;
    private javax.swing.JScrollPane panelCuotas;
    private javax.swing.JPanel panelPagoArriendo;
    private javax.swing.JLabel tituloCuotasArriendo;
    private javax.swing.JLabel tituloNumero;
    private javax.swing.JLabel tituloPagada;
    private javax.swing.JLabel tituloValor;
    // End of variables declaration//GEN-END:variables
}
