package com.mono_car_rent.modules.rental;

import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class RentalInterfase extends javax.swing.JFrame {

    /**
     * Creates new form Rental
     */
    public RentalInterfase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelArriendoCuotas = new javax.swing.JPanel();
        tituloArriendo = new javax.swing.JLabel();
        fechaArriendo = new javax.swing.JLabel();
        diasArriendo = new javax.swing.JLabel();
        precioDia = new javax.swing.JLabel();
        montoPagar = new javax.swing.JLabel();
        tituloCuotas = new javax.swing.JLabel();
        tituloValor = new javax.swing.JLabel();
        tituloPagada = new javax.swing.JLabel();
        tituloNumero = new javax.swing.JLabel();
        labelCantidadCuotas = new javax.swing.JLabel();
        guardarMostrarCuotas = new javax.swing.JButton();
        botonIngreso = new javax.swing.JButton();
        botonPagarPrimeraCuota = new javax.swing.JButton();
        seleccionCliente = new javax.swing.JComboBox<>();
        seleccionAutomovil = new javax.swing.JComboBox<>();
        valorFecha = new javax.swing.JTextField();
        valorDias = new javax.swing.JTextField();
        valorPrecio = new javax.swing.JTextField();
        valorMonto = new javax.swing.JTextField();
        valorCantidadCuotas = new javax.swing.JTextField();
        panelCuotas = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(782, 424));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelArriendoCuotas.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelArriendoCuotas.setMinimumSize(new java.awt.Dimension(782, 424));
        panelArriendoCuotas.setPreferredSize(new java.awt.Dimension(782, 424));

        tituloArriendo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloArriendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloArriendo.setText("ARRIENDOS CON CUOTAS");
        tituloArriendo.setToolTipText("");

        fechaArriendo.setText("Fecha Arriendo:");

        diasArriendo.setText("Días:");

        precioDia.setText("Precio por Día:");

        montoPagar.setText("MONTO A PAGAR");

        tituloCuotas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloCuotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCuotas.setText("CUOTAS A PAGAR");
        tituloCuotas.setToolTipText("");

        tituloValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloValor.setText("Valor");
        tituloValor.setToolTipText("");

        tituloPagada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloPagada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPagada.setText("¿pagada?");
        tituloPagada.setToolTipText("");

        tituloNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloNumero.setText("Numero");
        tituloNumero.setToolTipText("");

        labelCantidadCuotas.setText("Cantidad de cuotas:");

        guardarMostrarCuotas.setBackground(new java.awt.Color(220, 220, 220));
        guardarMostrarCuotas.setText("Guardar arriendo y mostrar cuotas >>");
        guardarMostrarCuotas.setAutoscrolls(true);
        guardarMostrarCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMostrarCuotasActionPerformed(evt);
            }
        });

        botonIngreso.setBackground(new java.awt.Color(220, 220, 220));
        botonIngreso.setText("Ingresar nuevo Cliente");
        botonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoActionPerformed(evt);
            }
        });

        botonPagarPrimeraCuota.setBackground(new java.awt.Color(220, 220, 220));
        botonPagarPrimeraCuota.setText("Pagar Primera Cuota");
        botonPagarPrimeraCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarPrimeraCuotaActionPerformed(evt);
            }
        });

        seleccionCliente.setBackground(new java.awt.Color(220, 220, 220));
        seleccionCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione CLIENTE", "Cliente 1", "Cliente 2", "Cliente 3", " " }));
        seleccionCliente.setMinimumSize(new java.awt.Dimension(160, 22));
        seleccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionClienteActionPerformed(evt);
            }
        });

        seleccionAutomovil.setBackground(new java.awt.Color(220, 220, 220));
        seleccionAutomovil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione AUTOMOVIL", "Cliente 1", "Cliente 2", "Cliente 3", " " }));

        valorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFechaActionPerformed(evt);
            }
        });

        valorDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorDiasActionPerformed(evt);
            }
        });

        valorMonto.setEditable(false);

        panelCuotas.setViewportView(jList1);

        javax.swing.GroupLayout panelArriendoCuotasLayout = new javax.swing.GroupLayout(panelArriendoCuotas);
        panelArriendoCuotas.setLayout(panelArriendoCuotasLayout);
        panelArriendoCuotasLayout.setHorizontalGroup(
            panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(seleccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(seleccionAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(botonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(tituloCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(529, 529, 529)
                .addComponent(tituloNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(tituloValor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(tituloPagada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addComponent(fechaArriendo)
                        .addGap(7, 7, 7)
                        .addComponent(valorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(diasArriendo)
                        .addGap(15, 15, 15)
                        .addComponent(valorDias, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addComponent(precioDia)
                        .addGap(13, 13, 13)
                        .addComponent(valorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addComponent(montoPagar)
                        .addGap(4, 4, 4)
                        .addComponent(valorMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(labelCantidadCuotas)
                        .addGap(5, 5, 5)
                        .addComponent(valorCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guardarMostrarCuotas))
                .addGap(56, 56, 56)
                .addComponent(panelCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(botonPagarPrimeraCuota))
        );
        panelArriendoCuotasLayout.setVerticalGroup(
            panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tituloArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(botonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(tituloCuotas)
                .addGap(6, 6, 6)
                .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloNumero)
                    .addComponent(tituloValor)
                    .addComponent(tituloPagada))
                .addGap(5, 5, 5)
                .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaArriendo)
                            .addComponent(valorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diasArriendo)
                            .addComponent(valorDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioDia)
                            .addComponent(valorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montoPagar)
                            .addComponent(valorMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addGroup(panelArriendoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCantidadCuotas)
                            .addComponent(valorCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(guardarMostrarCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArriendoCuotasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panelCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(botonPagarPrimeraCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(panelArriendoCuotas, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPagarPrimeraCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarPrimeraCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPagarPrimeraCuotaActionPerformed

    private void botonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresoActionPerformed

    private void valorDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDiasActionPerformed

    private void seleccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionClienteActionPerformed

        // Verificar si el usuario seleccionó "Seleccione CLIENTE"
        String seleccion = (String) seleccionCliente.getSelectedItem();

        if ("Seleccione CLIENTE".equals(seleccion)) {
            // Mostrar un mensaje si no se ha seleccionado un cliente válido
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente válido.");
        } else {
            // Continuar con el procesamiento si se selecciona un cliente válido
            System.out.println("Cliente seleccionado: " + seleccion);
            // Aquí puedes agregar el código para manejar la selección del cliente
        }
    }//GEN-LAST:event_seleccionClienteActionPerformed

    private void guardarMostrarCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMostrarCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarMostrarCuotasActionPerformed

    private void valorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFechaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngreso;
    private javax.swing.JButton botonPagarPrimeraCuota;
    private javax.swing.JLabel diasArriendo;
    private javax.swing.JLabel fechaArriendo;
    private javax.swing.JButton guardarMostrarCuotas;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel labelCantidadCuotas;
    private javax.swing.JLabel montoPagar;
    private javax.swing.JPanel panelArriendoCuotas;
    private javax.swing.JScrollPane panelCuotas;
    private javax.swing.JLabel precioDia;
    private javax.swing.JComboBox<String> seleccionAutomovil;
    private javax.swing.JComboBox<String> seleccionCliente;
    private javax.swing.JLabel tituloArriendo;
    private javax.swing.JLabel tituloCuotas;
    private javax.swing.JLabel tituloNumero;
    private javax.swing.JLabel tituloPagada;
    private javax.swing.JLabel tituloValor;
    private javax.swing.JTextField valorCantidadCuotas;
    private javax.swing.JTextField valorDias;
    private javax.swing.JTextField valorFecha;
    private javax.swing.JTextField valorMonto;
    private javax.swing.JTextField valorPrecio;
    // End of variables declaration//GEN-END:variables
}
